version: "3.8"

services:
  vault:
    build: .
    image: secure-vault-web:1.0
    container_name: secure-vault-web
    ports:
      - "9092"   # âœ… Fix: map container 8080 to host 8080
    volumes:
      - ./vault-data:/data   # persist your vault.csv locally
    restart: unless-stopped
